WITH
-- AGGREGATE MFGLOC VALUES
MFGLOC_AGG AS (
SELECT
A.FORMULA_ID,
STRING_AGG(S.DESCRIPTION, ', ') AS MFGLOC_COMBINED
FROM FSLOCATION S
JOIN FSFORMULAATTRIB A ON S.LOCATION_CODE = A.ATTRIB_VAL
WHERE A.ATTRIB_CODE = 'MFGLOC'
GROUP BY FORMULA_ID
),
-- RETRIEVE C_SUITABLE_FOR
ATTRIB_OTHER AS (
SELECT
FORMULA_ID,
MAX(CASE WHEN ATTRIB_CODE = 'C_SUITABLE_FOR' THEN ATTRIB_VAL END) AS C_SUITABLE_FOR
FROM FSFORMULAATTRIB
WHERE ATTRIB_CODE = 'C_SUITABLE_FOR'
GROUP BY FORMULA_ID
),




-- LABEL LOOKUP TABLES FOR FORMULA FIELDS
TYPE_LABEL AS (
SELECT
O.ENUM_VALUE AS C_TYPE_VALUE,
L.ENUM_LABEL AS C_TYPE_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_TYPE'
),




SUBFAMILY_LABEL AS (
SELECT
O.ENUM_VALUE AS C_SUBFAMILY_VALUE,
L.ENUM_LABEL AS C_SUBFAMILY_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_SUBFAMILY'
),




FLAVOUR_LABEL AS (
SELECT
O.ENUM_VALUE AS C_FLAVOUR_VALUE,
L.ENUM_LABEL AS C_FLAVOUR_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_FLAVOUR'
),




FAMILY_LABEL AS (
SELECT
O.ENUM_VALUE AS C_FAMILY_VALUE,
L.ENUM_LABEL AS C_FAMILY_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_FAMILY'
),




CATEGORY_LABEL AS (
SELECT
O.ENUM_VALUE AS C_CATEGORY_VALUE,
L.ENUM_LABEL AS C_CATEGORY_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_CATEGORY'
),




GAMMA_LABEL AS (
SELECT
O.ENUM_VALUE AS C_GAMMA_VALUE,
L.ENUM_LABEL AS C_GAMMA_LABEL
FROM FSVALIDATIONFIELD V
JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE
JOIN FSVALIDENUMLABELCF L ON L.ENUM_ORDER = O.ENUM_ORDER
AND V.ENUM_CODE = L.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
WHERE V.VALIDATION_CODE = 'FORMULA'
AND V.DB_FIELD_NAME = 'C_GAMMA'
),




-- BASE FOR ALL PARAMETERS INCLUDING BOTH ENUM & NUMERIC
PARAM_BASE AS (
SELECT
F.FORMULA_ID,
F.FORMULA_CODE,
F.VERSION,
F.DESCRIPTION,
F.CLASS,
I.C_ERPTEMPLATEITEM,
F.C_TYPE,
F.C_SUBFAMILY,
F.C_FLAVOUR,
F.C_FAMILY,
F.C_CATEGORY,
F.C_GAMMA,
P.PARAM_CODE,
MAX(P.PVALUE) AS PVALUE,
MAX(O.ENUM_VALUE) AS ENUM_VALUE,
MAX(L.ENUM_LABEL) AS ENUM_LABEL
FROM FSFORMULA F
JOIN FSFORMULATECHPARAM P ON P.FORMULA_ID = F.FORMULA_ID
JOIN FSFORMULASETS S ON S.FORMULA_ID = F.FORMULA_ID AND S.SET_CODE LIKE 'GLOBAL'
JOIN FSITEM I ON I.ITEM_CODE = F.ITEM_CODE AND I.C_ERPTEMPLATEITEM IN ('I02','I01')
LEFT JOIN FSVALIDATIONFIELD V ON V.VALIDATION_SUBCODE = P.PARAM_CODE
AND V.VALIDATION_CODE = 'G.TECHPVAL'
AND V.DB_FIELD_NAME = 'PVALUE'
LEFT JOIN FSVALIDENUMVALCF O ON V.ENUM_CODE = O.ENUM_CODE AND O.ENUM_VALUE = P.PVALUE
LEFT JOIN FSVALIDENUMLABELCF L ON L.ENUM_CODE = V.ENUM_CODE
AND L.LANGUAGE_CODE = 'IT-IT'
AND O.ENUM_ORDER = L.ENUM_ORDER
WHERE F.FORMULA_CODE NOT LIKE '%@%'
AND P.PARAM_CODE IN (
-- ENUM PARAMETERS
'ALLERGEN_WHEAT','ALLERGEN_TREENUTS','ALLERGEN_SOY','ALLERGEN_SO2',
'ALLERGEN_SESAME','ALLERGEN_PEANUTS','ALLERGEN_MUSTARD','ALLERGEN_MOLLUSCS',
'ALLERGEN_MILK','ALLERGEN_LUPIN','ALLERGEN_FISH','ALLERGEN_EGG',
'ALLERGEN_CRUSTACEA','ALLERGEN_CELERY','CERT_UTZ_HAZELNUTS','CERT_RSPO',
'CERT_RFA','CERT_IGP','CERT_FT','CERT_DOP','CERT_COCOA_HORIZONS',
'CERT_VEGAN','GMO_ROLLUP','C_CUSTOM_ITEM','PAESE_ULT_LAVORAZ',
'C_SPECIALTY','C_MONIT_PROD','NOMENCLATURA_DOGANAL','57_ORGANIC','52_KOSHER_SUITABLE',
'52_KOSHER','51_MUSLIM','51_HALAL_SUITABLE','50_VEGANS',
'50_COELIACS_20','50_COELIACS','49_VEGETARIANS','RD_CENTRE',
'PRODUCT_FORMAT','FSA_STATUS',
-- NUMERIC PARAMETERS
'SHELF_LIFE','SUGAR','SALT_EU_SODIUM_2.5','PROTEIN','POLYOLS',
'FIBER','FAT','FASAT_G','FAPU_G','FAMS_G','ENRGY_KCAL_CALC',
'ENERGY_KJ_CALC','CARBS_CALC','ALCOHOL','15_SODIUM_100',
'14_ASH','STARCH','QU_METODO_RIC','QU_GEST_LOTTI',
'QU_CONTR_QUAL','MOISTURE'
)
GROUP BY
F.FORMULA_ID,
F.FORMULA_CODE,
F.VERSION,
F.DESCRIPTION,
F.CLASS,
I.C_ERPTEMPLATEITEM,
F.C_TYPE,
F.C_SUBFAMILY,
F.C_FLAVOUR,
F.C_FAMILY,
F.C_CATEGORY,
F.C_GAMMA,
P.PARAM_CODE
),




-- FIRST PIVOT TO GET ONE ROW PER FORMULA WITH ALL PARAMETER VALUES
PIVOT_ALL_VALUES AS (
SELECT *
FROM (
SELECT
FORMULA_ID,
FORMULA_CODE,
VERSION,
DESCRIPTION,
CLASS,
C_ERPTEMPLATEITEM,
C_TYPE,
C_SUBFAMILY,
C_FLAVOUR,
C_FAMILY,
C_CATEGORY,
C_GAMMA,
PARAM_CODE,
PVALUE
FROM PARAM_BASE
) AS SRC
PIVOT (
MAX(PVALUE)
FOR PARAM_CODE IN (
[ALLERGEN_WHEAT],[ALLERGEN_TREENUTS],[ALLERGEN_SOY],[ALLERGEN_SO2],
[ALLERGEN_SESAME],[ALLERGEN_PEANUTS],[ALLERGEN_MUSTARD],[ALLERGEN_MOLLUSCS],
[ALLERGEN_MILK],[ALLERGEN_LUPIN],[ALLERGEN_FISH],[ALLERGEN_EGG],
[ALLERGEN_CRUSTACEA],[ALLERGEN_CELERY],[CERT_UTZ_HAZELNUTS],[CERT_RSPO],
[CERT_RFA],[CERT_IGP],[CERT_FT],[CERT_DOP],[CERT_COCOA_HORIZONS],
[CERT_VEGAN],[GMO_ROLLUP],[C_CUSTOM_ITEM],[PAESE_ULT_LAVORAZ],
[C_SPECIALTY],[NOMENCLATURA_DOGANAL],[57_ORGANIC],[52_KOSHER_SUITABLE],
[52_KOSHER],[51_MUSLIM],[51_HALAL_SUITABLE],[50_VEGANS],
[50_COELIACS_20],[50_COELIACS],[49_VEGETARIANS],[RD_CENTRE],[C_MONIT_PROD],
[PRODUCT_FORMAT],[FSA_STATUS],
[SHELF_LIFE],[SUGAR],[SALT_EU_SODIUM_2.5],[PROTEIN],[POLYOLS],
[FIBER],[FAT],[FASAT_G],[FAPU_G],[FAMS_G],[ENRGY_KCAL_CALC],
[ENERGY_KJ_CALC],[CARBS_CALC],[ALCOHOL],[15_SODIUM_100],
[14_ASH],[STARCH],[QU_METODO_RIC],[QU_GEST_LOTTI],
[QU_CONTR_QUAL],[MOISTURE]
)
) AS P
),




-- SECOND PIVOT TO GET ENUM LABELS WHERE NEEDED
PIVOT_ENUM_LABELS AS (
SELECT *
FROM (
SELECT
FORMULA_ID,
PARAM_CODE,
ENUM_LABEL
FROM PARAM_BASE
WHERE PARAM_CODE IN (
'ALLERGEN_WHEAT','ALLERGEN_TREENUTS','ALLERGEN_SOY','ALLERGEN_SO2',
'ALLERGEN_SESAME','ALLERGEN_PEANUTS','ALLERGEN_MUSTARD','ALLERGEN_MOLLUSCS',
'ALLERGEN_MILK','ALLERGEN_LUPIN','ALLERGEN_FISH','ALLERGEN_EGG',
'ALLERGEN_CRUSTACEA','ALLERGEN_CELERY','CERT_UTZ_HAZELNUTS','CERT_RSPO',
'CERT_RFA','CERT_IGP','CERT_FT','CERT_DOP','CERT_COCOA_HORIZONS',
'CERT_VEGAN','GMO_ROLLUP','C_CUSTOM_ITEM','PAESE_ULT_LAVORAZ',
'C_SPECIALTY','NOMENCLATURA_DOGANAL','57_ORGANIC','52_KOSHER_SUITABLE',
'52_KOSHER','51_MUSLIM','51_HALAL_SUITABLE','50_VEGANS',
'50_COELIACS_20','50_COELIACS','49_VEGETARIANS','RD_CENTRE',
'PRODUCT_FORMAT','FSA_STATUS','QU_METODO_RIC','QU_GEST_LOTTI','QU_CONTR_QUAL','C_MONIT_PROD'
)
) AS SRC
PIVOT (
MAX(ENUM_LABEL)
FOR PARAM_CODE IN (
[ALLERGEN_WHEAT],[ALLERGEN_TREENUTS],[ALLERGEN_SOY],[ALLERGEN_SO2],
[ALLERGEN_SESAME],[ALLERGEN_PEANUTS],[ALLERGEN_MUSTARD],[ALLERGEN_MOLLUSCS],
[ALLERGEN_MILK],[ALLERGEN_LUPIN],[ALLERGEN_FISH],[ALLERGEN_EGG],
[ALLERGEN_CRUSTACEA],[ALLERGEN_CELERY],[CERT_UTZ_HAZELNUTS],[CERT_RSPO],
[CERT_RFA],[CERT_IGP],[CERT_FT],[CERT_DOP],[CERT_COCOA_HORIZONS],
[CERT_VEGAN],[GMO_ROLLUP],[C_CUSTOM_ITEM],[PAESE_ULT_LAVORAZ],
[C_SPECIALTY],[NOMENCLATURA_DOGANAL],[57_ORGANIC],[52_KOSHER_SUITABLE],
[52_KOSHER],[51_MUSLIM],[51_HALAL_SUITABLE],[50_VEGANS],
[50_COELIACS_20],[50_COELIACS],[49_VEGETARIANS],[RD_CENTRE],[C_MONIT_PROD],
[PRODUCT_FORMAT],[FSA_STATUS],[QU_METODO_RIC],[QU_GEST_LOTTI],[QU_CONTR_QUAL]
)
) AS P
)




-- FINAL COMBINED SELECT
SELECT
V.FORMULA_ID,
V.FORMULA_CODE,
V.VERSION,
V.DESCRIPTION,
V.CLASS,
V.C_ERPTEMPLATEITEM,

-- ORIGINAL CODE VALUES
--V.C_TYPE,
--V.C_SUBFAMILY,
--V.C_FLAVOUR,
--V.C_FAMILY,
--V.C_CATEGORY,
-- V.C_GAMMA,

-- LABEL VALUES
T.C_TYPE_LABEL,
S.C_SUBFAMILY_LABEL,
FL.C_FLAVOUR_LABEL,
FA.C_FAMILY_LABEL,
C.C_CATEGORY_LABEL,
G.C_GAMMA_LABEL,

ATTR.C_SUITABLE_FOR,
MFG.MFGLOC_COMBINED,

-- ALL OTHER PARAMETERS (ENUM AND NUMERIC)
COALESCE(L.[ALLERGEN_WHEAT], V.[ALLERGEN_WHEAT]) AS ALLERGEN_WHEAT,
COALESCE(L.[ALLERGEN_TREENUTS], V.[ALLERGEN_TREENUTS]) AS ALLERGEN_TREENUTS,
COALESCE(L.[ALLERGEN_SOY], V.[ALLERGEN_SOY]) AS ALLERGEN_SOY,
COALESCE(L.[ALLERGEN_SO2], V.[ALLERGEN_SO2]) AS ALLERGEN_SO2,
COALESCE(L.[ALLERGEN_SESAME], V.[ALLERGEN_SESAME]) AS ALLERGEN_SESAME,
COALESCE(L.[ALLERGEN_PEANUTS], V.[ALLERGEN_PEANUTS]) AS ALLERGEN_PEANUTS,
COALESCE(L.[ALLERGEN_MUSTARD], V.[ALLERGEN_MUSTARD]) AS ALLERGEN_MUSTARD,
COALESCE(L.[ALLERGEN_MOLLUSCS], V.[ALLERGEN_MOLLUSCS]) AS ALLERGEN_MOLLUSCS,
COALESCE(L.[ALLERGEN_MILK], V.[ALLERGEN_MILK]) AS ALLERGEN_MILK,
COALESCE(L.[ALLERGEN_LUPIN], V.[ALLERGEN_LUPIN]) AS ALLERGEN_LUPIN,
COALESCE(L.[ALLERGEN_FISH], V.[ALLERGEN_FISH]) AS ALLERGEN_FISH,
COALESCE(L.[ALLERGEN_EGG], V.[ALLERGEN_EGG]) AS ALLERGEN_EGG,
COALESCE(L.[ALLERGEN_CRUSTACEA], V.[ALLERGEN_CRUSTACEA]) AS ALLERGEN_CRUSTACEA,
COALESCE(L.[ALLERGEN_CELERY], V.[ALLERGEN_CELERY]) AS ALLERGEN_CELERY,
COALESCE(L.[CERT_UTZ_HAZELNUTS], V.[CERT_UTZ_HAZELNUTS]) AS CERT_UTZ_HAZELNUTS,
COALESCE(L.[CERT_RSPO], V.[CERT_RSPO]) AS CERT_RSPO,
COALESCE(L.[CERT_RFA], V.[CERT_RFA]) AS CERT_RFA,
COALESCE(L.[CERT_IGP], V.[CERT_IGP]) AS CERT_IGP,
COALESCE(L.[CERT_FT], V.[CERT_FT]) AS CERT_FT,
COALESCE(L.[CERT_DOP], V.[CERT_DOP]) AS CERT_DOP,
COALESCE(L.[CERT_COCOA_HORIZONS], V.[CERT_COCOA_HORIZONS]) AS CERT_COCOA_HORIZONS,
COALESCE(L.[CERT_VEGAN], V.[CERT_VEGAN]) AS CERT_VEGAN,
COALESCE(L.[GMO_ROLLUP], V.[GMO_ROLLUP]) AS GMO_ROLLUP,
COALESCE(L.[C_CUSTOM_ITEM], V.[C_CUSTOM_ITEM]) AS C_CUSTOM_ITEM,
COALESCE(L.[PAESE_ULT_LAVORAZ], V.[PAESE_ULT_LAVORAZ]) AS PAESE_ULT_LAVORAZ,
COALESCE(L.[C_SPECIALTY], V.[C_SPECIALTY]) AS C_SPECIALTY,
COALESCE(L.[NOMENCLATURA_DOGANAL], V.[NOMENCLATURA_DOGANAL]) AS NOMENCLATURA_DOGANAL,
COALESCE(L.[57_ORGANIC], V.[57_ORGANIC]) AS [57_ORGANIC],
COALESCE(L.[52_KOSHER], V.[52_KOSHER]) AS [52_KOSHER],
COALESCE(L.[52_KOSHER_SUITABLE], V.[52_KOSHER_SUITABLE]) AS [52_KOSHER_SUITABLE],
COALESCE(L.[51_MUSLIM], V.[51_MUSLIM]) AS [51_MUSLIM],
COALESCE(L.[51_HALAL_SUITABLE], V.[51_HALAL_SUITABLE]) AS [51_HALAL_SUITABLE],
COALESCE(L.[50_VEGANS], V.[50_VEGANS]) AS [50_VEGANS],
COALESCE(L.[50_COELIACS], V.[50_COELIACS]) AS [50_COELIACS],
COALESCE(L.[50_COELIACS_20], V.[50_COELIACS_20]) AS [50_COELIACS_20],
COALESCE(L.[49_VEGETARIANS], V.[49_VEGETARIANS]) AS [49_VEGETARIANS],
COALESCE(L.[RD_CENTRE], V.[RD_CENTRE]) AS RD_CENTRE,
COALESCE(L.[PRODUCT_FORMAT], V.[PRODUCT_FORMAT]) AS PRODUCT_FORMAT,
COALESCE(L.[FSA_STATUS], V.[FSA_STATUS]) AS FSA_STATUS,
COALESCE(L.[QU_METODO_RIC], V.[QU_METODO_RIC]) AS QU_METODO_RIC,
COALESCE(L.[QU_GEST_LOTTI], V.[QU_GEST_LOTTI]) AS QU_GEST_LOTTI,
COALESCE(L.[QU_CONTR_QUAL], V.[QU_CONTR_QUAL]) AS QU_CONTR_QUAL,
COALESCE(L.[C_MONIT_PROD], V.[C_MONIT_PROD]) AS C_MONIT_PROD,

V.[SHELF_LIFE], V.[SUGAR], V.[SALT_EU_SODIUM_2.5],
V.[PROTEIN], V.[POLYOLS], V.[FIBER], V.[FAT],
V.[FASAT_G], V.[FAPU_G], V.[FAMS_G], V.[ENRGY_KCAL_CALC],
V.[ENERGY_KJ_CALC], V.[CARBS_CALC], V.[ALCOHOL],
V.[15_SODIUM_100], V.[14_ASH], V.[STARCH],
V.[MOISTURE]




FROM PIVOT_ALL_VALUES V
LEFT JOIN PIVOT_ENUM_LABELS L ON V.FORMULA_ID = L.FORMULA_ID
LEFT JOIN ATTRIB_OTHER ATTR ON V.FORMULA_ID = ATTR.FORMULA_ID
LEFT JOIN MFGLOC_AGG MFG ON V.FORMULA_ID = MFG.FORMULA_ID
LEFT JOIN TYPE_LABEL T ON V.C_TYPE = T.C_TYPE_VALUE
LEFT JOIN SUBFAMILY_LABEL S ON V.C_SUBFAMILY = S.C_SUBFAMILY_VALUE
LEFT JOIN FLAVOUR_LABEL FL ON V.C_FLAVOUR = FL.C_FLAVOUR_VALUE
LEFT JOIN FAMILY_LABEL FA ON V.C_FAMILY = FA.C_FAMILY_VALUE
LEFT JOIN CATEGORY_LABEL C ON V.C_CATEGORY = C.C_CATEGORY_VALUE
LEFT JOIN GAMMA_LABEL G ON V.C_GAMMA = G.C_GAMMA_VALUE





ORDER BY V.FORMULA_ID


OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
--OFFSET 1000 ROWS FETCH NEXT 2000 ROWS ONLY;
--OFFSET 2000 ROWS FETCH NEXT 3000 ROWS ONLY;
--OFFSET 3000 ROWS FETCH NEXT 4000 ROWS ONLY;
--OFFSET 4000 ROWS FETCH NEXT 5000 ROWS ONLY;
--OFFSET 5000 ROWS FETCH NEXT 6000 ROWS ONLY;
--OFFSET 6000 ROWS FETCH NEXT 7000 ROWS ONLY;