WITH DOCPIVOT AS
(
-- PIVOT FSDOC DATA INTO COLUMNS
SELECT
P.FORMULA_ID,
P.FORMULA_CODE,
P.VERSION,
P.DESCRIPTION,
P.C_TDS_LANGUAGE,
P.C_TDS_COUNTRY_ORIG,
P.C_GMTG7_PUBLISH,
P.C_TRANSLATION_TYPE,
P.C_REPORT_LAUNCH_NUM,
P.[LEGAL NAME/DENOMINATION],
P.[SENSORY_DESCRIPTION],
P.[INGREDIENT_DEC],
P.[USAGE_INSTRUCTIONS],
P.[MICROBIOLOGICAL_STANDARDS],
P.[TYPICAL_VALUES]
FROM
(
SELECT
F.FORMULA_ID,
F.FORMULA_CODE,
F.VERSION,
F.DESCRIPTION,
F.C_TDS_LANGUAGE,
F.C_TDS_COUNTRY_ORIG,
F.C_GMTG7_PUBLISH,
F.C_TRANSLATION_TYPE,
F.C_REPORT_LAUNCH_NUM,
D.FUNCTION_CODE,
D.TEXT_DATA
FROM FSFORMULA F
JOIN FSDOC D
ON F.DOC_ID = D.DOC_ID
WHERE F.FORMULA_CODE + '\' + F.VERSION = '01982489\001'
AND D.FUNCTION_CODE IN (
'LEGAL NAME/DENOMINATION',
'SENSORY_DESCRIPTION',
'INGREDIENT_DEC',
'USAGE_INSTRUCTIONS',
'MICROBIOLOGICAL_STANDARDS',
'TYPICAL_VALUES'
)
) SRC
PIVOT
(
MAX(TEXT_DATA)
FOR FUNCTION_CODE IN (
[LEGAL NAME/DENOMINATION],
[SENSORY_DESCRIPTION],
[INGREDIENT_DEC],
[USAGE_INSTRUCTIONS],
[MICROBIOLOGICAL_STANDARDS],
[TYPICAL_VALUES]
)
) P
),


PARAMAGG AS
(
SELECT
M.FORMULA_ID,


-- ALLERGENS + CERTIFICATES (EXISTING CODE)
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_TREENUTS' THEN M.PVALUE END) AS ALLERGEN_TREENUTS_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_TREENUTS' THEN M.ATTRIBUTE1 END) AS ALLERGEN_TREENUTS_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_PEANUTS' THEN M.PVALUE END) AS ALLERGEN_PEANUTS_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_PEANUTS' THEN M.ATTRIBUTE1 END) AS ALLERGEN_PEANUTS_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SESAME' THEN M.PVALUE END) AS ALLERGEN_SESAME_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SESAME' THEN M.ATTRIBUTE1 END) AS ALLERGEN_SESAME_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_WHEAT' THEN M.PVALUE END) AS ALLERGEN_WHEAT_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_WHEAT' THEN M.ATTRIBUTE1 END) AS ALLERGEN_WHEAT_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_CRUSTACEA' THEN M.PVALUE END) AS ALLERGEN_CRUSTACEA_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_CRUSTACEA' THEN M.ATTRIBUTE1 END) AS ALLERGEN_CRUSTACEA_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_EGG' THEN M.PVALUE END) AS ALLERGEN_EGG_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_EGG' THEN M.ATTRIBUTE1 END) AS ALLERGEN_EGG_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_FISH' THEN M.PVALUE END) AS ALLERGEN_FISH_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_FISH' THEN M.ATTRIBUTE1 END) AS ALLERGEN_FISH_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SOY' THEN M.PVALUE END) AS ALLERGEN_SOY_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SOY' THEN M.ATTRIBUTE1 END) AS ALLERGEN_SOY_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MILK' THEN M.PVALUE END) AS ALLERGEN_MILK_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MILK' THEN M.ATTRIBUTE1 END) AS ALLERGEN_MILK_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_CELERY' THEN M.PVALUE END) AS ALLERGEN_CELERY_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_CELERY' THEN M.ATTRIBUTE1 END) AS ALLERGEN_CELERY_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MUSTARD' THEN M.PVALUE END) AS ALLERGEN_MUSTARD_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MUSTARD' THEN M.ATTRIBUTE1 END) AS ALLERGEN_MUSTARD_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MOLLUSCS' THEN M.PVALUE END) AS ALLERGEN_MOLLUSCS_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_MOLLUSCS' THEN M.ATTRIBUTE1 END) AS ALLERGEN_MOLLUSCS_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SO2' THEN M.PVALUE END) AS ALLERGEN_SO2_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_SO2' THEN M.ATTRIBUTE1 END) AS ALLERGEN_SO2_SOURCE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_LUPIN' THEN M.PVALUE END) AS ALLERGEN_LUPIN_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ALLERGEN_LUPIN' THEN M.ATTRIBUTE1 END) AS ALLERGEN_LUPIN_SOURCE,


-- CERTIFICATES / OTHER PARAMS
MAX(CASE WHEN M.PARAM_CODE = 'CERT_UTZ_HAZELNUTS' THEN M.PVALUE END) AS CERT_UTZ_HAZELNUTS_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_UTZ_HAZELNUTS' THEN M.ATTRIBUTE2 END) AS CERT_UTZ_HAZELNUTS_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_UTZ_COCOA' THEN M.PVALUE END) AS CERT_UTZ_COCOA_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_UTZ_COCOA' THEN M.ATTRIBUTE2 END) AS CERT_UTZ_COCOA_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_FT' THEN M.PVALUE END) AS CERT_FT_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_FT' THEN M.ATTRIBUTE2 END) AS CERT_FT_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_RSPO' THEN M.PVALUE END) AS CERT_RSPO_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_RSPO' THEN M.ATTRIBUTE2 END) AS CERT_RSPO_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_DOP' THEN M.PVALUE END) AS CERT_DOP_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_DOP' THEN M.ATTRIBUTE2 END) AS CERT_DOP_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_IGP' THEN M.PVALUE END) AS CERT_IGP_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_IGP' THEN M.ATTRIBUTE2 END) AS CERT_IGP_NOTES,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_ALTROMERCATO' THEN M.PVALUE END) AS CERT_ALTROMERCATO_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CERT_ALTROMERCATO' THEN M.ATTRIBUTE2 END) AS CERT_ALTROMERCATO_NOTES,


-- NUMBERED PARAMS
MAX(CASE WHEN M.PARAM_CODE = '57_ORGANIC' THEN M.PVALUE END) AS [57_ORGANIC_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '57_ORGANIC' THEN M.ATTRIBUTE2 END) AS [57_ORGANIC_NOTES],
MAX(CASE WHEN M.PARAM_CODE = '49_VEGETARIANS' THEN M.PVALUE END) AS [49_VEGETARIANS_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '50_VEGANS' THEN M.PVALUE END) AS [50_VEGANS_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '52_KOSHER_SUITABLE' THEN M.PVALUE END) AS [52_KOSHER_SUITABLE_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '52_KOSHER' THEN M.PVALUE END) AS [52_KOSHER_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '52_KOSHER' THEN M.ATTRIBUTE2 END) AS [52_KOSHER_NOTES],
MAX(CASE WHEN M.PARAM_CODE = '51_HALAL_SUITABLE' THEN M.PVALUE END) AS [51_HALAL_SUITABLE_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '51_MUSLIM' THEN M.PVALUE END) AS [51_MUSLIM_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '51_MUSLIM' THEN M.ATTRIBUTE2 END) AS [51_MUSLIM_NOTES],
MAX(CASE WHEN M.PARAM_CODE = '50_COELIACS' THEN M.PVALUE END) AS [50_COELIACS_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = '50_COELIACS_20' THEN M.PVALUE END) AS [50_COELIACS_20_PVALUE],


-- NUTRITION PARAMS (PVALUE ONLY)
MAX(CASE WHEN M.PARAM_CODE = 'ENERGY_KJ_CALC' THEN M.PVALUE END) AS ENERGY_KJ_CALC_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'ENRGY_KCAL_CALC' THEN M.PVALUE END) AS ENRGY_KCAL_CALC_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'FAT' THEN M.PVALUE END) AS FAT_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'FASAT_G' THEN M.PVALUE END) AS FASAT_G_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'FAMS_G' THEN M.PVALUE END) AS FAMS_G_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'FAPU_G' THEN M.PVALUE END) AS FAPU_G_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CARBS_CALC' THEN M.PVALUE END) AS CARBS_CALC_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'CALC_AVAIL_CARB' THEN M.PVALUE END) AS CALC_AVAIL_CARB_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'SUGAR' THEN M.PVALUE END) AS SUGAR_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'STARCH' THEN M.PVALUE END) AS STARCH_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'POLYOLS' THEN M.PVALUE END) AS POLYOLS_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'SUGAR_ADD' THEN M.PVALUE END) AS SUGAR_ADD_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'FIBER' THEN M.PVALUE END) AS FIBER_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'PROTEIN' THEN M.PVALUE END) AS PROTEIN_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'SALT_EU_SODIUM_2.5' THEN M.PVALUE END) AS SALT_EU_SODIUM_2_5_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'SODIUM' THEN M.PVALUE END) AS SODIUM_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = 'MOISTURE' THEN M.PVALUE END) AS MOISTURE_PVALUE,
MAX(CASE WHEN M.PARAM_CODE = '14_ASH' THEN M.PVALUE END) AS [14_ASH_PVALUE],
MAX(CASE WHEN M.PARAM_CODE = 'ALCOHOL' THEN M.PVALUE END) AS ALCOHOL_PVALUE


FROM FSFORMULATECHPARAM M
WHERE M.PARAM_CODE IN (
'ALLERGEN_TREENUTS','ALLERGEN_PEANUTS','ALLERGEN_SESAME','ALLERGEN_WHEAT',
'ALLERGEN_CRUSTACEA','ALLERGEN_EGG','ALLERGEN_FISH','ALLERGEN_SOY','ALLERGEN_MILK',
'ALLERGEN_CELERY','ALLERGEN_MUSTARD','ALLERGEN_MOLLUSCS','ALLERGEN_SO2','ALLERGEN_LUPIN',
'CERT_UTZ_HAZELNUTS','CERT_UTZ_COCOA','CERT_FT','CERT_RSPO','CERT_DOP','CERT_IGP','CERT_ALTROMERCATO',
'57_ORGANIC','49_VEGETARIANS','50_VEGANS','52_KOSHER_SUITABLE','52_KOSHER','51_HALAL_SUITABLE',
'51_MUSLIM','50_COELIACS','50_COELIACS_20',
'ENERGY_KJ_CALC','ENRGY_KCAL_CALC','FAT','FASAT_G','FAMS_G','FAPU_G','CARBS_CALC','CALC_AVAIL_CARB',
'SUGAR','STARCH','POLYOLS','SUGAR_ADD','FIBER','PROTEIN','SALT_EU_SODIUM_2.5','SODIUM','MOISTURE',
'14_ASH','ALCOHOL'
)
GROUP BY M.FORMULA_ID
)


SELECT
D.FORMULA_CODE,
D.DESCRIPTION,
D.VERSION,
D.C_TDS_LANGUAGE,
D.C_TDS_COUNTRY_ORIG,
D.C_GMTG7_PUBLISH,
D.C_TRANSLATION_TYPE,
D.C_REPORT_LAUNCH_NUM,
D.[LEGAL NAME/DENOMINATION],
D.[SENSORY_DESCRIPTION],
D.[INGREDIENT_DEC],
D.[USAGE_INSTRUCTIONS],
D.[MICROBIOLOGICAL_STANDARDS],
D.[TYPICAL_VALUES],


P.ALLERGEN_TREENUTS_PVALUE,
P.ALLERGEN_TREENUTS_SOURCE,
P.ALLERGEN_PEANUTS_PVALUE,
P.ALLERGEN_PEANUTS_SOURCE,
P.ALLERGEN_SESAME_PVALUE,
P.ALLERGEN_SESAME_SOURCE,
P.ALLERGEN_WHEAT_PVALUE,
P.ALLERGEN_WHEAT_SOURCE,
P.ALLERGEN_CRUSTACEA_PVALUE,
P.ALLERGEN_CRUSTACEA_SOURCE,
P.ALLERGEN_EGG_PVALUE,
P.ALLERGEN_EGG_SOURCE,
P.ALLERGEN_FISH_PVALUE,
P.ALLERGEN_FISH_SOURCE,
P.ALLERGEN_SOY_PVALUE,
P.ALLERGEN_SOY_SOURCE,
P.ALLERGEN_MILK_PVALUE,
P.ALLERGEN_MILK_SOURCE,
P.ALLERGEN_CELERY_PVALUE,
P.ALLERGEN_CELERY_SOURCE,
P.ALLERGEN_MUSTARD_PVALUE,
P.ALLERGEN_MUSTARD_SOURCE,
P.ALLERGEN_MOLLUSCS_PVALUE,
P.ALLERGEN_MOLLUSCS_SOURCE,
P.ALLERGEN_SO2_PVALUE,
P.ALLERGEN_SO2_SOURCE,
P.ALLERGEN_LUPIN_PVALUE,
P.ALLERGEN_LUPIN_SOURCE,


P.CERT_UTZ_HAZELNUTS_PVALUE,
P.CERT_UTZ_HAZELNUTS_NOTES,
P.CERT_UTZ_COCOA_PVALUE,
P.CERT_UTZ_COCOA_NOTES,
P.CERT_FT_PVALUE,
P.CERT_FT_NOTES,
P.CERT_RSPO_PVALUE,
P.CERT_RSPO_NOTES,
P.CERT_DOP_PVALUE,
P.CERT_DOP_NOTES,
P.CERT_IGP_PVALUE,
P.CERT_IGP_NOTES,
P.CERT_ALTROMERCATO_PVALUE,
P.CERT_ALTROMERCATO_NOTES,


P.[57_ORGANIC_PVALUE],
P.[57_ORGANIC_NOTES],
P.[49_VEGETARIANS_PVALUE],
P.[50_VEGANS_PVALUE],
P.[52_KOSHER_SUITABLE_PVALUE],
P.[52_KOSHER_PVALUE],
P.[52_KOSHER_NOTES],
P.[51_HALAL_SUITABLE_PVALUE],
P.[51_MUSLIM_PVALUE],
P.[51_MUSLIM_NOTES],
P.[50_COELIACS_PVALUE],
P.[50_COELIACS_20_PVALUE],


-- NUTRITION PVALUE COLUMNS
P.ENERGY_KJ_CALC_PVALUE,
P.ENRGY_KCAL_CALC_PVALUE,
P.FAT_PVALUE,
P.FASAT_G_PVALUE,
P.FAMS_G_PVALUE,
P.FAPU_G_PVALUE,
P.CARBS_CALC_PVALUE,
P.CALC_AVAIL_CARB_PVALUE,
P.SUGAR_PVALUE,
P.STARCH_PVALUE,
P.POLYOLS_PVALUE,
P.SUGAR_ADD_PVALUE,
P.FIBER_PVALUE,
P.PROTEIN_PVALUE,
P.SALT_EU_SODIUM_2_5_PVALUE,
P.SODIUM_PVALUE,
P.MOISTURE_PVALUE,
P.[14_ASH_PVALUE],
P.ALCOHOL_PVALUE


FROM DOCPIVOT D
LEFT JOIN PARAMAGG P
ON D.FORMULA_ID = P.FORMULA_ID;
