SELECT DISTINCT FSLOCATION.PARENT_CODE
FROM FSFORMULA
JOIN FSFORMULAATTRIB ON FSFORMULA.FORMULA_ID = FSFORMULAATTRIB.FORMULA_ID
JOIN FSLOCATION ON FSFORMULAATTRIB.ATTRIB_VAL = FSLOCATION.LOCATION_CODE
WHERE ((FSFORMULA.ITEM_CODE=[%1]
AND FSFORMULA.STATUS_IND >= 600 AND FSFORMULA.STATUS_IND < 800)
OR FSFORMULA.FORMULA_CODE= [%2])
AND FSLOCATION.PARENT_CODE <> ''
AND FSLOCATION.PARENT_CODE IS NOT NULL
AND FSFORMULAATTRIB.ATTRIB_CODE = 'MFGLOC'