--Description: This script examines the database to determine the most recent instance when a user approved a workflow. If the approval timeframe has expired for the associated user or role,
--the script fetches the corresponding formula and dispatches a notification to the relevant user or role through the interface.


SELECT
S.ROLE_CODE,
S.GROUP_CODE,
F.FORMULA_CODE AS OBJ_FORMULA_CODE,
F.VERSION,
F.STATUS_IND AS FORMULA_STATUS,
F.DESCRIPTION AS FORMULA_DESCRIPTION,
F.CLASS AS FORMULA_CLASS,
S.SOURCE_USER_CODE,
S.ACTIONWIP_ID,
W.ACTIONSET_CODE,
W.WIP_COMMENT,
W.DESCRIPTION AS WF_DESCRIPTION,
S.DESCRIPTION AS ACTION_DESCRIPTION,
P.PVALUE AS WF_REASON_PVALUE,
F.DATE_IND AS FORMULA_DATE_IND,
I.ITEM_CODE,
I.STATUS_IND AS ITEM_STATUS,
I.DESCRIPTION AS ITEM_DESCRIPTION,
I.CLASS AS ITEM_CLASS,
I.DATE_IND AS ITEM_DATE_IND
FROM
FSACTIONWIPSTEPS S
INNER JOIN
FSACTIONWIP W ON W.ACTIONWIP_ID = S.ACTIONWIP_ID
LEFT JOIN
FSFORMULA F ON F.FORMULA_CODE + '\' + F.VERSION = S.TARGET_OBJECT_KEY
LEFT JOIN
FSITEM I ON I.ITEM_CODE = S.TARGET_OBJECT_KEY
LEFT JOIN
FSACTIONWIPPARAM P ON P.ACTIONWIP_ID = S.ACTIONWIP_ID
AND P.PARAM_CODE = 'WF_REASON'
WHERE
W.ACTIONSET_CODE IN ('SO_FP_NEWLABEL_APPROVAL_IS_EU','SO_ITEM_ALT_SUPPLIER_IR_EU','SO_ITEM_ALT_SUPPLIER_IR_IT','SO_ITEM_SITE_EXTENSION_IR_EU',
'SO_ITEM_SITE_EXTENSION_IR_IT','SO_PKG_APPROVAL_IR_EU','SO_PKG_APPROVAL_IR_IT','SO_PKG_CHANGE_IR_EU','SO_PKG_CHANGE_IR_IT',
'SO_PREPRINT_PKG_APPROVAL_IR_EU','SO_PREPRINT_PKG_APPROVAL_IR_IT','SO_RM_APPROVAL_1_IR_EU','SO_RM_APPROVAL_2_IR_EU','SO_RM_APPROVAL_1_IR_IT',
'SO_RM_APPROVAL_2_IR_IT','SO_RM_CHANGE_IR_EU','SO_RM_CHANGE_IR_IT')
AND S.ACTION_CODE IN ('SO_NEW_FRM_APPR_REJ_IS_EU','SO_ITEM_APPR_REJ_IR_EU','SO_ITEM_APPR_REJ_IR_IT')
AND S.QUEUE_STATUS_IND = '1'

AND (
(
(W.ACTIONSET_CODE IN ('SO_RM_APPROVAL_1_IR_IT', 'SO_RM_APPROVAL_1_IR_EU')
AND (
(S.ROLE_CODE IN ('RL_PUR', 'RL_PUR_IS_EU', 'RL_RMRA_IS_EU', 'RL_RMRA')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -2, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -2, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -2, GETDATE())))
OR
(S.GROUP_CODE LIKE 'QA_%'
AND S.ACTUAL_START_DATE < DATEADD(MINUTE, -2160, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(MINUTE, -2160, GETDATE()))
OR (I.DATE_IND < DATEADD(MINUTE, -2160, GETDATE())))
)
)
)
OR (
(W.ACTIONSET_CODE IN ('SO_RM_APPROVAL_2_IR_IT','SO_RM_APPROVAL_2_IR_EU','SO_RM_CHANGE_IR_EU','SO_RM_CHANGE_IR_IT','SO_ITEM_ALT_SUPPLIER_IR_EU','SO_ITEM_ALT_SUPPLIER_IR_IT')
AND (
(S.ROLE_CODE IN ('RL_RMRA_IS_EU', 'RL_RMRA')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -2, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -2, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -2, GETDATE())))
OR
((S.GROUP_CODE LIKE 'QA_%' OR S.ROLE_CODE IN ('RL_CERT_QA','RL_PUR','RL_PUR_IS_EU'))
AND S.ACTUAL_START_DATE < DATEADD(DAY, -1, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -1, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -1, GETDATE())))
)
)
)
OR (
(W.ACTIONSET_CODE IN ('SO_ITEM_SITE_EXTENSION_IR_EU','SO_ITEM_SITE_EXTENSION_IR_IT','SO_PREPRINT_PKG_APPROVAL_IR_EU','SO_PREPRINT_PKG_APPROVAL_IR_IT')
AND (
((S.ROLE_CODE IN ('RL_RMRA_IS_EU', 'RL_RMRA','RL_PUR','RL_PUR_IS_EU','RL_PK_SPEC','RL_RAPACK','RL_RAPACK_IS_EU') OR S.GROUP_CODE LIKE 'QA_%')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -1, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -1, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -1, GETDATE())))
)
)
)
OR (
(W.ACTIONSET_CODE IN ('SO_ITEM_SITE_EXTENSION_IR_EU','SO_ITEM_SITE_EXTENSION_IR_IT','SO_PREPRINT_PKG_APPROVAL_IR_EU','SO_PREPRINT_PKG_APPROVAL_IR_IT','SO_PKG_CHANGE_IR_EU','SO_PKG_CHANGE_IR_T')
AND (
((S.ROLE_CODE IN ('RL_RMRA_IS_EU', 'RL_RMRA','RL_PUR','RL_PUR_IS_EU','RL_PK_SPEC','RL_RAPACK','RL_RAPACK_IS_EU','RL_PK_SPEC') OR S.GROUP_CODE LIKE 'QA_%')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -1, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -1, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -1, GETDATE())))
)
)
)
OR (
(W.ACTIONSET_CODE IN ('SO_PKG_APPROVAL_IR_EU','SO_PKG_APPROVAL_IR_EU')
AND (
((S.ROLE_CODE = 'RL_PK_SPEC')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -1, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -1, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -1, GETDATE())))
OR
((S.GROUP_CODE LIKE 'QA_%')
AND S.ACTUAL_START_DATE < DATEADD(DAY, -2, GETDATE()) AND (COALESCE(F.DATE_IND, I.DATE_IND) IS NULL)
OR (F.DATE_IND < DATEADD(DAY, -2, GETDATE()))
OR (I.DATE_IND < DATEADD(DAY, -2, GETDATE())))
)
)
)
);