SELECT A.ACTIONWIP_ID , F.FORMULA_CODE , F.VERSION FROM FSFORMULA F


LEFT JOIN FSACTIONWIPSTEPS A ON A.TARGET_OBJECT_KEY = F.FORMULA_CODE + '\' + F.VERSION


LEFT JOIN FSACTIONWIPPARAM P ON P.ACTIONWIP_ID = A.ACTIONWIP_ID


WHERE F.FORMULA_CODE + '\' + F.VERSION LIKE [%1] AND A.ACTION_CODE LIKE [%2]